### PR TITLE
add stc8 support and debug support

### PR DESCRIPTION
**Pull request by totollo**
add stc8 support and debug support. please upgrade stcgal to v1.6 to flash stc8 chips.

### CODE REVIEW

**Comment by ivankravets** [comment]
Are these new versions compatible with the existing boards?

**Comment by totollo** [comment]
> Are these new versions compatible with the existing boards?

yes. I enabled sdcc debug build flags and linking flags to get *.cdb file.

**Comment by ivankravets** [comment]
We will back to this PR soon. Need to find these new packages.

**Comment by totollo** [comment]
> We will back to this PR soon. Need to find these new packages.

thx

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platform-intel_mcs51/pull/41

**Pull request closed without merging**
